apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/DeividFrancis/homelab.git
    targetRevision: main
    path: monitoring-chart
    helm:
      valueFiles:
        - monitoring-chart/loki-stack-values.yml
        - monitoring-chart/grafana-agent-values.yml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
