apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: evolution-api
          image: atendai/evolution-api:v2.1.1
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: {{ .Values.configmap.name }}
          env:
            - name: AUTHENTICATION_API_KEY
              valueFrom:
                secretKeyRef:
                  name: vault-evolution-api-key
                  key: AUTHENTICATION_API_KEY
          volumeMounts:
            - name: evolution-pvc-store
              mountPath: "/evolution/instances"
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
      volumes:
        - name: evolution-pvc-store
          persistentVolumeClaim:
            claimName: evolution-pvc
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "vault-evolution"