apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: vault-evolution
spec:
  provider: vault
  secretObjects:
    - data:
      - key: AUTHENTICATION_API_KEY
        objectName: authentication-api-key
      secretName: vault-evolution-api-key
      type: Opaque
  parameters:
    vaultAddress: "http://vault.vault:8200"
    roleName: "role-evolution"
    objects: |
      - objectName: "authentication-api-key"
        secretPath: "pantulab/data/evolution"
        secretKey: "AUTHENTICATION_API_KEY"