apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5678"
        vault.hashicorp.com/role: "role-n8n"
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-status: "update"
        vault.hashicorp.com/agent-inject-secret-n8n: "pantulab/n8n"
        vault.hashicorp.com/agent-inject-template-env: |
          {{- with secret "pantulab/n8n" -}}
            export N8N_ENCRYPTION_KEY="{{ .Data.data.N8N_ENCRYPTION_KEY }}"
          {{- end }}
      labels:
        app: n8n
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: n8n
          image: n8nio/n8n:latest
          command: ["sh", "-c"]
          args: ["source /vault/secrets/env && tini -- /docker-entrypoint.sh"]
          ports:
            - containerPort: 5678
          envFrom:
            - configMapRef:
                name: n8n-config-map
          volumeMounts:
            - name: n8n-pvc-store
              mountPath: "/home/node/.n8n"
          resources:
            limits:
              cpu: "300m"
              memory: "512Mi"
            requests:
              cpu: "50m"
              memory: "128Mi"
      volumes:
        - name: n8n-pvc-store
          persistentVolumeClaim:
            claimName: n8n-pvc
