apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n
  template:
    metadata:
      labels:
        app: n8n
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      volumes:
        - name: n8n-pv-store
          persistentVolumeClaim:
            claimName: n8n-pv-claim
      containers:
        - name: n8n
          image: docker.n8n.io/n8nio/n8n
          ports:
            - containerPort: 5678
          volumeMounts:
            - mountPath: "/home/node/.n8n"
              name: n8n-pv-store
          # resources:
          #   limits:
          #     cpu: "500m"
          #     memory: "1Gi"
