name: evolution-api
configmap:
  name: evolution-configmap

# Estou usando Vault CSI
podAnnotations: {}
# podAnnotations:
#   # prometheus.io/scrape: "true"
#   vault.hashicorp.com/role: "role-evolution"
#   vault.hashicorp.com/agent-inject: "true"
#   vault.hashicorp.com/agent-inject-status: "update"
#   vault.hashicorp.com/agent-inject-secret-evolution: "pantulab/evolution"
#   vault.hashicorp.com/agent-inject-template-env: |
#     {{- with secret "pantulab/evolution" -}}
#       export AUTHENTICATION_API_KEY="{{ .Data.data.AUTHENTICATION_API_KEY }}"
#     {{- end }}

postgresql:
  fullnameOverride: postgres
  image:
    tag: 17.2.0
  auth:
    password: wNWL525liqSlZFdl
    username: postgres

  commonLabels:
    name: postgres
    component: database
    manager: helm

global:
  redis:
    password: redispass
