loki-stack:
  loki:
    enabled: true
    auth_enabled: false
    persistence:
      enabled: true
      size: 1Gi
    resources:
      limits:
        cpu: "500m"
        memory: "1Gi"
      requests:
        cpu: "100m"
        memory: "256Mi"

  promtail:
    enabled: true
    podAnnotations:
      prometheus.io/scrape: "true"
    resources:
      limits:
        cpu: "500m"
        memory: "1Gi"
      requests:
        cpu: "100m"
        memory: "256Mi"

    config:
      logLevel: debug
      clients:
        - url: http://{{ .Release.Name }}-loki:3100/loki/api/v1/push

  prometheus:
    enabled: true

  grafana:
    enabled: true
    image:
      tag: "11.5.1"
    sidecar:
      datasources:
        enabled: true
        initDatasources: true
    # Provision grafana-dashboards-kubernetes
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
          - name: "grafana-dashboards-kubernetes"
            orgId: 1
            folder: "Kubernetes"
            type: file
            disableDeletion: true
            editable: true
            options:
              path: /var/lib/grafana/dashboards/grafana-dashboards-kubernetes
          - name: "grafana-dashboards-node-exporter"
            orgId: 1
            folder: "Node Exporter"
            type: file
            disableDeletion: true
            editable: true
            options:
              path: /var/lib/grafana/dashboards/grafana-dashboards-node-exporter
    dashboards:
      grafana-dashboards-node-exporter:
        node-exporter-full:
          url: https://raw.githubusercontent.com/rfmoz/grafana-dashboards/refs/heads/master/prometheus/node-exporter-full.json
          token: ""
      grafana-dashboards-kubernetes:
        k8s-system-api-server:
          url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-system-api-server.json
          token: ""
        k8s-system-coredns:
          url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-system-coredns.json
          token: ""
        k8s-views-global:
          url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-global.json
          token: ""
        k8s-views-namespaces:
          url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-namespaces.json
          token: ""
        k8s-views-nodes:
          url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-nodes.json
          token: ""
        k8s-views-pods:
          url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-pods.json
          token: ""
    podAnnotations:
      annotations: |
      vault.hashicorp.com/role: "role-monitoring"
      vault.hashicorp.com/agent-init-first: "true"
      vault.hashicorp.com/agent-inject: "true"
      vault.hashicorp.com/agent-inject-status: "update"
      vault.hashicorp.com/agent-inject-secret-monitoring: "pantulab/monitoring"
      vault.hashicorp.com/agent-inject-template-password: |
        {{- with secret "pantulab/monitoring" -}}
          {{ .Data.data.grafana_password }}
        {{- end }}
    env:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD__FILE: /vault/secrets/password
    service:
      type: ClusterIP
